FROM elixir:1.12.0

ENV RUST_VERSION=1.54.0

WORKDIR /tmp

RUN set -ex && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        gcc \
        libc6-dev \
        wget && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
      -y --profile minimal --default-toolchain $RUST_VERSION -c component add rustfmt clippy
WORKDIR /var/opt/app
