[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.arm-unknown-linux-gnueabihf]
image="ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main"
dockerfile = "./cross/Dockerfile"


[target.aarch64-unknown-linux-gnu]
image="ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
dockerfile = "./cross/Dockerfile"

[target.aarch64-unknown-linux-musl]
image="ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
dockerfile = "./cross/Dockerfile"

[target.riscv64gc-unknown-linux-gnu]
image="ghcr.io/cross-rs/riscv64gc-unknown-linux-gnu:main"
dockerfile = "./cross/Dockerfile"

[target.x86_64-unknown-linux-gnu]
image="ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
dockerfile = "./cross/Dockerfile"

[target.x86_64-unknown-linux-musl]
image="ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"
dockerfile = "./cross/Dockerfile"

