name: Code Coverage

on: [pull_request]

jobs:
  coverage:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.13.4' # Define the elixir version [required]
          otp-version: '25.3' # Define the OTP version [required]
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
            components: rustfmt, clippy
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
            deps
            _build
          key: coverage-${{ runner.os }}-rust-${{ matrix.rust }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: coverage-${{ runner.os }}-rust-${{ matrix.rust }}-mix-


      - name: Install dependencies
        run: mix deps.get
      - name: start epmd daemon for cluster tests
        run: epmd -daemon
      - name: Run tests with coverage
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
